[project]
name = "rogo-earth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.0.1",
    "leafmap>=0.45.0",
    "pyproj>=3.7.1",
    "shapely>=2.1.0",
    "streamlit>=1.45.1",
]
